Models/AddFilmViewModel.cs
namespace ShopUKW2025.Models
{
    public class AddFilmViewModel
    {
        public List<Category> AllCategories { get; set; }

        public Film NewFilm { get; set; }

        public IFormFile Poster { get; set; }
    }
}

Models/Film.cs
using System.ComponentModel.DataAnnotations;

namespace ShopUKW2025.Models
{
    public class Film
    {
        public int FilmId { get; set; }

        [Required]
        public string Title { get; set; }

        public string Director { get; set; }

        [StringLength(500)]
        public string Desc { get; set; }

        public string Poster { get; set; }

        public decimal? Price { get; set; }

        public int CategoryId { get; set; }

        public Category Category { get; set; }
    }
}

Controllers/CartController.cs
using Microsoft.AspNetCore.Mvc;
using ShopUKW2025.DAL;
using ShopUKW2025.Infrastructure;
using ShopUKW2025.Models;

namespace ShopUKW2025.Controllers
{
    public class CartController : Controller
    {
        FilmsContext db;

        public CartController(FilmsContext db)
        {
            this.db = db;
        }

        public IActionResult Index()
        {

            var cart = CartManager.GetItems(HttpContext.Session);

            ViewBag.Total = CartManager.GetCartValue(HttpContext.Session);


            return View(cart);
        }

        public IActionResult AddToCart(int filmId)
        {
            CartManager.AddToCart(HttpContext.Session, db, filmId);
            return RedirectToAction("Index");
        }

        public IActionResult RemoveFromCart(int id)
        {
            var model = new RemoveViewModel()
            {
                itemQuantity = CartManager.RemoveFromCart(HttpContext.Session, id),
                itemId = id,
                cartValue = CartManager.GetCartValue(HttpContext.Session)
            };

            return Json(model);


        }
    }
}

Controllers/FilmsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ShopUKW2025.DAL;
using ShopUKW2025.Models;

namespace ShopUKW2025.Controllers
{
    public class FilmsController : Controller
    {
        FilmsContext db;
        IWebHostEnvironment webHost;


       


        public FilmsController(FilmsContext db, IWebHostEnvironment webHost)
        {
            this.db = db;
            this.webHost = webHost;
        }

        [HttpGet]
        public IActionResult AddFilm()
        {
            var model = new AddFilmViewModel();
            model.AllCategories = db.Categories.ToList();

            return View(model);
        }

        [HttpPost]
        public IActionResult AddFilm(AddFilmViewModel model)
        {
            

            var picFolderPath = Path.Combine(webHost.WebRootPath, "grafiki");

            var uniqueName = Guid.NewGuid() + "_" + model.Poster.FileName;

            var filePath = Path.Combine(picFolderPath, uniqueName);

            model.Poster.CopyTo(new FileStream(filePath, FileMode.Create));


            model.NewFilm.Poster = uniqueName;


            db.Films.Add(model.NewFilm);
            db.SaveChanges();

            return RedirectToAction("Details", new { filmId = model.NewFilm.FilmId });
        }



        public IActionResult Wszystkie()
        {
            var films = db.Films.ToList();
            return View(films);
        }

        public IActionResult ProductList(string categoryName)
        {
            var category =  db.Categories.Include("Films").Where(c => c.Name == categoryName).Single();

            var films = category.Films.ToList();

            return View(films);
        }

        public IActionResult Details(int filmId)
        {
            db.Categories.Find(db.Films.Find(filmId).CategoryId);

            var film = db.Films.Find(filmId);

            return View(film);
        }

        [HttpPost]
        public IActionResult Search(string tekst)
        {
            var filmy = from f in db.Films select f;
            ViewBag.Fraza = tekst;

            if(!String.IsNullOrEmpty(tekst))
            {
                filmy = filmy.Where(f => f.Title.ToUpper().Contains(tekst.ToUpper()));
                return View(filmy.ToList());
            }

            return RedirectToAction("Index", "Home");

            
        }


        [HttpGet]
        public IActionResult EditFilm(int id)
        {
            var film = db.Films.Find(id);

            return View(film);
        }

        [HttpPost]
        public IActionResult EditFilm(Film film)
        {
            var filmDB = db.Films.Find(film.FilmId);
            
            if(filmDB != null)
            {
                filmDB.Title = film.Title;
                filmDB.Director = film.Director;
                filmDB.Desc = film.Desc;
                filmDB.Price = film.Price;

                db.Entry(filmDB).State = EntityState.Modified;
                db.SaveChanges();
            }
            return RedirectToAction("Details", new { filmId = filmDB.FilmId });
        }
    }
}

ViewComponents/SideMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ShopUKW2025.DAL;
using ShopUKW2025.Models;

namespace ShopUKW2025.ViewComponents
{
    public class SideMenuViewComponent : ViewComponent
    {

        FilmsContext db;

        public SideMenuViewComponent(FilmsContext db)
        {
            this.db = db;
        }

        public async Task<IViewComponentResult> InvokeAsync(string categoryName)
        {

            var category = db.Categories.Include("Films").Where(c => c.Name == categoryName).FirstOrDefault();

            var films = new List<Film>();
            

            if (category != null)
            {
                films = category.Films.OrderBy(f => f.Title).ToList();
                
            }

            return await Task.FromResult(View("_SideMenu", films));
            
        }
    }
}

Views/Films/AddFilm.cshtml
@model AddFilmViewModel


@Html.BeginForm("AddFilm", "Films", FormMethod.Post, new { enctype = "multipart/form-data" })
{
	<div class= "mb-3">
	@Html.LabelFor(m => m.NewFilm.Title, "Tytył:", new { @class = "form-label" })
	@Html.TextBoxFor(m => m.NewFilm.Title, new { @class = "form-control", @required=true })

	</div>

<div class="mb-3">
	@Html.LabelFor(m => m.NewFilm.Director, "Reżyser:", new { @class = "form-label" })
	@Html.TextBoxFor(m => m.NewFilm.Director, new { @class = "form-control", @required = true })

</div>

<div class="mb-3">
	@Html.LabelFor(m => m.NewFilm.Desc, "Opis:", new { @class = "form-label" })
	@Html.TextBoxFor(m => m.NewFilm.Desc, new { @class = "form-control", @required = true })

</div>

<div class="mb-3">
	@Html.LabelFor(m => m.NewFilm.Price, "Cena:", new { @class = "form-label" })
	@Html.TextBoxFor(m => m.NewFilm.Price, new { @class = "form-control", @required = true })

</div>


<div class="mb-3">
	@Html.LabelFor(m=> m.Poster, "Plakat", new { @class = "form-label" })
	@Html.TextBoxFor(m=> m.Poster, new { Type = "file", @class = "form-control" })

<div class="mb-3">
	@foreach(var cat in Model.AllCategories){
		@Html.RadioButtonFor(m => m.NewFilm.CategoryId, cat.CategoryId, new { @class = "form-check-input" })
		@cat.Name
		<br />

	}
</div>

<div class="mb-3">
<button type="submit" class="btn btn-secondary">Dodaj</button>
</div>
}

Views/Films/Details.cshtml
@model Film

<table>
    <tr>
        <td>
            <h2> @Model.Category.Name </h2>
@(await Component.InvokeAsync("SideMenu", new { categoryName = Model.Category.Name }))
</td>

<td>
    <h2>Obrazek</h2>
    <img src="~/grafiki/@Model.Poster" height="400px"/>

</td>



<td>

<ul>

    <li>Tytuł: @Model.Title</li>
    <li>Reżyser: @Model.Director</li>
    <li>Cena: @Model.Price</li>
    <li>Opis: @Model.Desc</li>
</ul>

            <button class="btn btn-secondary" onclick="window.location.href='@Url.Action("AddToCart", "Cart", new { filmId = Model.FilmId })'">Dodaj do koszyka 🛒</button>
<button class="btn btn-primary" onclick="window.location.href='@Url.Action("EditFilm", "Films", new { id = Model.FilmId})'">Edytuj</button>
</td>
</tr>
</table>

Views/Films/EditFilm.cshtml
@model Film

@using (Html.BeginForm("EditFilm", "Films", FormMethod.Post))
{
@Html.HiddenFor(f => f.CategoryId)
@Html.HiddenFor(f => f.Poster)
@Html.HiddenFor(f => f.FilmId)

<table>
    <tr>
        <td>
            @* <h2> @Model.Category.Name </h2> *@
@* @(await Component.InvokeAsync("SideMenu", new { categoryName = Model.Category.Name }))  *@
</td>

<td>
    <h2>Obrazek</h2>
    <img src="~/grafiki/@Model.Poster" height="400px"/>

</td>



<td>

<ul>

    <li>Tytuł: @Html.TextBoxFor(f => f.Title, new { @class = "form-control" })</li>
    <li>Reżyser: @Html.TextBoxFor(f => f.Director, new { @class = "form-control" })</li>
    <li>Cena: @Html.TextBoxFor(f => f.Price, new { @class = "form-control" })</li>
    <li>Opis: @Html.TextAreaFor(f => f.Desc, new { @class = "form-control" })</li>
</ul>
                <button class="btn btn-primary" type="submit"> Zapisz zmiany</button>
</td>
</tr>
</table>

//<button class ="btn btn-primary" type="submit"> Zapisz zmiany</button>
}

Views/Films/ProductList.cshtml
@model IEnumerable<Film>
@{
    ViewData["Title"] = "Kategoria" + Model.First().Category.Name;
}


<table class="table">
    <thead>
        <tr>
            <th>Tytuł filmu</th>
            <th>Reżyser</th>
            <th>Opis</th>
            <th>Cena</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var film in Model)
        {
            
        
        <tr>

            <td>@film.Title</td>
            <td>@film.Director</td>
            <td>@film.Desc</td>
            <td>@film.Price</td>
            <td><a href="@Url.Action("Details", "Films", new {filmId = film.FilmId})">a</a></td>
        </tr>
        }
    </tbody>
</table>

Views/Films/Search.cshtml
@model IEnumerable<Film>

<h3>
    @Html.Raw("Filmy zawierające: " + ViewBag.Fraza)
</h3>

<table class="table table-striped">
    <thead>
        <tr>
            <th>Tytuł filmu</th>
            <th>Reżyser</th>
            <th>Opis</th>
            <th>Cena</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var film in Model)
        {


            <tr>

                <td>@film.Title</td>
                <td>@film.Director</td>
                <td>@film.Desc</td>
                <td>@film.Price zł</td>
                <td><a href="@Url.Action("Details", "Films", new { filmId = film.FilmId })">🔎</a></td>
            </tr>
        }
    </tbody>
</table>

Views/Films/Wszystkie.cshtml
@model IEnumerable<Film>

<div class="row">
    @foreach (var film in Model)
    {
        <div class="col-md-3">
            <a href="@Url.Action("Details", "Films", new { filmId = film.FilmId })">
                <img src="~/grafiki/@film.Poster" alt="Film @film.Poster" class="movie-poster" height="200px" />
            </a>
        </div>
    }
</div>